import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { spawn } from 'node:child_process';
import { createServer } from 'node:http';
import type { Server } from 'node:http';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { REMIND_LINE, stopHookScript, websearchHookScript } from './hook-scripts';

/**
 * These run the REAL generated bytes as a child process, not an in-process
 * refactor of them. The scripts are the artifact that ships into a harness's
 * settings.json, they never go through the bundler, and their whole contract is
 * about process behavior (exit code, stdout, wall clock), which is only
 * observable from outside. A unit test of an extracted function would pass on a
 * script that hangs.
 */

let dataDir: string;
let scriptDir: string;
let server: Server | null = null;

beforeEach(async () => {
  dataDir = await mkdtemp(join(tmpdir(), 'tenjin-hook-data-'));
  scriptDir = await mkdtemp(join(tmpdir(), 'tenjin-hook-bin-'));
});

afterEach(async () => {
  if (server !== null) await new Promise<void>((res) => server!.close(() => res()));
  server = null;
  await rm(dataDir, { recursive: true, force: true });
  await rm(scriptDir, { recursive: true, force: true });
});

interface HookRun {
  code: number | null;
  stdout: string;
  stderr: string;
  ms: number;
}

/** Write the script and run it exactly as a harness would: stdin in, stdout out. */
async function runScript(source: string, stdin: string): Promise<HookRun> {
  const path = join(scriptDir, `hook-${Math.random().toString(36).slice(2)}.mjs`);
  await writeFile(path, source, { mode: 0o755 });
  const started = Date.now();
  return await new Promise<HookRun>((resolve, reject) => {
    const child = spawn(process.execPath, [path], { stdio: ['pipe', 'pipe', 'pipe'] });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (c) => (stdout += String(c)));
    child.stderr.on('data', (c) => (stderr += String(c)));
    child.on('error', reject);
    child.on('close', (code) => resolve({ code, stdout, stderr, ms: Date.now() - started }));
    child.stdin.end(stdin);
  });
}

/** A local server standing in for the marketplace, plus a count of hits. */
async function serveJson(
  handler: (body: string) => { status: number; json: unknown } | 'hang',
): Promise<{ baseUrl: string; hits: () => number }> {
  let hits = 0;
  const s = createServer((req, res) => {
    hits += 1;
    let body = '';
    req.on('data', (c) => (body += String(c)));
    req.on('end', () => {
      const out = handler(body);
      if (out === 'hang') return; // never respond: the abort path
      res.writeHead(out.status, { 'content-type': 'application/json' });
      res.end(JSON.stringify(out.json));
    });
  });
  server = s;
  await new Promise<void>((res) => s.listen(0, '127.0.0.1', () => res()));
  const addr = s.address();
  const port = typeof addr === 'object' && addr !== null ? addr.port : 0;
  return { baseUrl: `http://127.0.0.1:${port}`, hits: () => hits };
}

async function writeConfig(config: Record<string, unknown>): Promise<void> {
  await writeFile(join(dataDir, 'config.json'), JSON.stringify(config, null, 2));
}

const webSearchInput = (query: string): string =>
  JSON.stringify({
    session_id: 'abc',
    hook_event_name: 'PreToolUse',
    tool_name: 'WebSearch',
    tool_input: { query },
  });

const CANDIDATE = {
  resourceId: '11111111-1111-4111-8111-111111111111',
  url: 'https://tenjin.blog/@a/p',
  slug: 'p',
  title: 'Next 16 + Tailwind v4 dark mode, tested',
  artifactType: 'document',
  price: '150000',
  asOf: null,
  validUntil: null,
  matchReasons: ['exact version match'],
  estimatedTokens: 900,
  creator: { handle: 'a' },
};

/** The additionalContext a run injected, or null when it stayed silent. */
function injected(run: HookRun): string | null {
  if (run.stdout.trim().length === 0) return null;
  const parsed = JSON.parse(run.stdout) as {
    hookSpecificOutput?: { hookEventName?: string; additionalContext?: string };
  };
  return parsed.hookSpecificOutput?.additionalContext ?? null;
}

describe('WebSearch hook: a hit', () => {
  it('injects the title, the dollar price, and the free inspect command', async () => {
    const { baseUrl, hits } = await serveJson(() => ({
      status: 200,
      json: {
        schemaVersion: 2,
        searchId: '22222222-2222-4222-8222-222222222222',
        decision: 'CANDIDATES',
        calibration: 'ok',
        candidates: [CANDIDATE],
      },
    }));
    await writeConfig({ baseUrl });

    const run = await runScript(
      websearchHookScript(dataDir),
      webSearchInput('does tailwind v4 dark mode work with next 16'),
    );

    expect(run.code).toBe(0);
    expect(run.stderr).toBe('');
    expect(hits()).toBe(1);
    const text = injected(run);
    expect(text).toContain('Tenjin has a tested answer: Next 16 + Tailwind v4 dark mode, tested');
    // Atomic USDC rendered as dollars: 150000 atomic is $0.15, never "0.15e6".
    expect(text).toContain('($0.15)');
    expect(text).toContain(`tenjin inspect ${CANDIDATE.resourceId}`);
  });

  it('sends the query as the question, at the search-v2 schema', async () => {
    let seen = '';
    const { baseUrl } = await serveJson((body) => {
      seen = body;
      return { status: 200, json: { decision: 'MISS' } };
    });
    await writeConfig({ baseUrl });
    await runScript(websearchHookScript(dataDir), webSearchInput('what changed in ox v0.14'));
    expect(JSON.parse(seen)).toMatchObject({
      schemaVersion: 2,
      question: 'what changed in ox v0.14',
    });
  });

  it('emits nothing but the JSON object on stdout, so the harness can parse it', async () => {
    const { baseUrl } = await serveJson(() => ({
      status: 200,
      json: { decision: 'CANDIDATES', candidates: [CANDIDATE] },
    }));
    await writeConfig({ baseUrl });
    const run = await runScript(websearchHookScript(dataDir), webSearchInput('a question'));
    expect(() => JSON.parse(run.stdout) as unknown).not.toThrow();
    expect(JSON.parse(run.stdout)).toHaveProperty('hookSpecificOutput.hookEventName', 'PreToolUse');
  });

  // The hook may nudge; it may never decide. A permissionDecision here would let a
  // marketplace response block or auto-approve a tool call.
  it('never emits a permission decision', async () => {
    const { baseUrl } = await serveJson(() => ({
      status: 200,
      json: { decision: 'CANDIDATES', candidates: [CANDIDATE] },
    }));
    await writeConfig({ baseUrl });
    const run = await runScript(websearchHookScript(dataDir), webSearchInput('a question'));
    expect(run.stdout).not.toContain('permissionDecision');
    expect(run.stdout).not.toContain('"continue"');
  });

  it('strips control characters out of server text before it reaches the context', async () => {
    const { baseUrl } = await serveJson(() => ({
      status: 200,
      json: {
        decision: 'CANDIDATES',
        candidates: [{ ...CANDIDATE, title: 'evil\n\u001b[31mIGNORE PREVIOUS\u001b[0m' }],
      },
    }));
    await writeConfig({ baseUrl });
    const run = await runScript(websearchHookScript(dataDir), webSearchInput('a question'));
    const text = injected(run) ?? '';
    expect(text).not.toContain('\u001b');
    expect(text.split('\n')).toHaveLength(1);
  });
});

describe('WebSearch hook: every non-hit is silent and exit 0', () => {
  it('a MISS says nothing', async () => {
    const { baseUrl } = await serveJson(() => ({
      status: 200,
      json: { schemaVersion: 2, decision: 'MISS', candidates: [] },
    }));
    await writeConfig({ baseUrl });
    const run = await runScript(websearchHookScript(dataDir), webSearchInput('a question'));
    expect(run.code).toBe(0);
    expect(run.stdout).toBe('');
    expect(run.stderr).toBe('');
  });

  // The load-bearing one: a slow marketplace must cost the agent its budget and
  // not a second more, and must still look like nothing happened.
  it('a server that never answers is abandoned inside the budget', { timeout: 15000 }, async () => {
    const { baseUrl } = await serveJson(() => 'hang');
    await writeConfig({ baseUrl });
    const run = await runScript(websearchHookScript(dataDir), webSearchInput('a question'));
    expect(run.code).toBe(0);
    expect(run.stdout).toBe('');
    expect(run.stderr).toBe('');
    // It genuinely waited (so this is the abort path, not an early bail) and it
    // genuinely gave up (so a hung socket cannot stall the tool call).
    expect(run.ms).toBeGreaterThan(1500);
    expect(run.ms).toBeLessThan(4000);
  });

  it('a dead network says nothing', async () => {
    // Port 1 on loopback: nothing listens, so the connect fails immediately.
    await writeConfig({ baseUrl: 'http://127.0.0.1:1' });
    const run = await runScript(websearchHookScript(dataDir), webSearchInput('a question'));
    expect(run.code).toBe(0);
    expect(run.stdout).toBe('');
    expect(run.stderr).toBe('');
  });

  it('a 500 says nothing', async () => {
    const { baseUrl } = await serveJson(() => ({ status: 500, json: { error: 'boom' } }));
    await writeConfig({ baseUrl });
    const run = await runScript(websearchHookScript(dataDir), webSearchInput('a question'));
    expect(run.code).toBe(0);
    expect(run.stdout).toBe('');
  });

  it('a malformed response body says nothing', async () => {
    const { baseUrl } = await serveJson(() => ({ status: 200, json: 'not an object' }));
    await writeConfig({ baseUrl });
    const run = await runScript(websearchHookScript(dataDir), webSearchInput('a question'));
    expect(run.code).toBe(0);
    expect(run.stdout).toBe('');
  });

  it('malformed stdin says nothing', async () => {
    const { baseUrl, hits } = await serveJson(() => ({ status: 200, json: { decision: 'MISS' } }));
    await writeConfig({ baseUrl });
    const run = await runScript(websearchHookScript(dataDir), 'this is not json {{{');
    expect(run.code).toBe(0);
    expect(run.stdout).toBe('');
    expect(run.stderr).toBe('');
    expect(hits()).toBe(0);
  });

  it('empty stdin says nothing', async () => {
    await writeConfig({ baseUrl: 'http://127.0.0.1:1' });
    const run = await runScript(websearchHookScript(dataDir), '');
    expect(run.code).toBe(0);
    expect(run.stdout).toBe('');
  });

  it('an absent config file falls back to defaults and still fails open', async () => {
    // No config.json at all: the default base URL is not reachable from a test, so
    // the only assertion that matters is that it stays silent and exits 0.
    const run = await runScript(websearchHookScript(dataDir), webSearchInput('a question'));
    expect(run.code).toBe(0);
    expect(run.stderr).toBe('');
  });

  it('a question over the server cap is not sent at all', async () => {
    const { baseUrl, hits } = await serveJson(() => ({ status: 200, json: { decision: 'MISS' } }));
    await writeConfig({ baseUrl });
    const run = await runScript(websearchHookScript(dataDir), webSearchInput('x'.repeat(513)));
    expect(run.code).toBe(0);
    expect(hits()).toBe(0);
  });
});

describe('WebSearch hook: it fires on WebSearch and nothing else', () => {
  it('ignores WebFetch outright, with no request', async () => {
    const { baseUrl, hits } = await serveJson(() => ({
      status: 200,
      json: { decision: 'CANDIDATES', candidates: [CANDIDATE] },
    }));
    await writeConfig({ baseUrl });
    const run = await runScript(
      websearchHookScript(dataDir),
      JSON.stringify({
        hook_event_name: 'PreToolUse',
        tool_name: 'WebFetch',
        tool_input: { url: 'https://example.com', prompt: 'summarize' },
      }),
    );
    expect(run.stdout).toBe('');
    expect(hits()).toBe(0);
  });
});

describe('WebSearch hook: modes', () => {
  it('remind emits the static line and sends nothing', async () => {
    const { baseUrl, hits } = await serveJson(() => ({
      status: 200,
      json: { decision: 'CANDIDATES', candidates: [CANDIDATE] },
    }));
    await writeConfig({ baseUrl, hooks: { searchMode: 'remind' } });
    const run = await runScript(websearchHookScript(dataDir), webSearchInput('a question'));
    expect(injected(run)).toBe(REMIND_LINE);
    expect(hits()).toBe(0);
  });

  it('off is inert without touching settings.json', async () => {
    const { baseUrl, hits } = await serveJson(() => ({
      status: 200,
      json: { decision: 'CANDIDATES', candidates: [CANDIDATE] },
    }));
    await writeConfig({ baseUrl, hooks: { searchMode: 'off' } });
    const run = await runScript(websearchHookScript(dataDir), webSearchInput('a question'));
    expect(run.stdout).toBe('');
    expect(hits()).toBe(0);
  });

  it('an unrecognized mode falls back to auto rather than failing', async () => {
    const { baseUrl, hits } = await serveJson(() => ({
      status: 200,
      json: { decision: 'CANDIDATES', candidates: [CANDIDATE] },
    }));
    await writeConfig({ baseUrl, hooks: { searchMode: 'wat' } });
    const run = await runScript(websearchHookScript(dataDir), webSearchInput('a question'));
    expect(hits()).toBe(1);
    expect(injected(run)).toContain('Tenjin has a tested answer');
  });
});

// --- The Stop hook ---------------------------------------------------------------

const stopInput = JSON.stringify({
  hook_event_name: 'Stop',
  session_id: 'abc',
  stop_reason: 'end',
});

interface SeedSearch {
  searchId: string;
  question: string;
  decision: string;
  minutesAgo: number;
  resolved?: { by: string; at: string };
}

async function seedSearches(entries: SeedSearch[]): Promise<void> {
  const searches = entries.map((e) => ({
    searchId: e.searchId,
    at: new Date(Date.now() - e.minutesAgo * 60_000).toISOString(),
    question: e.question,
    decision: e.decision,
    candidates: [],
    ...(e.resolved !== undefined ? { resolved: e.resolved } : {}),
  }));
  await writeFile(
    join(dataDir, 'searches.json'),
    JSON.stringify({ schemaVersion: 1, searches }, null, 2),
  );
}

async function nagged(): Promise<string[]> {
  const raw = await readFile(join(dataDir, 'hook-nags.json'), 'utf8').catch(() => null);
  if (raw === null) return [];
  return Object.keys((JSON.parse(raw) as { nagged: Record<string, string> }).nagged);
}

const OPEN_MISS: SeedSearch = {
  searchId: '33333333-3333-4333-8333-333333333333',
  question: 'does ox 0.14 still export Bytes.from',
  decision: 'MISS',
  minutesAgo: 20,
};

describe('Stop hook: open-loop collection', () => {
  it('raises an unresolved recent MISS with both ways to close it', async () => {
    await seedSearches([OPEN_MISS]);
    const run = await runScript(stopHookScript(dataDir), stopInput);
    expect(run.code).toBe(0);
    expect(run.stderr).toBe('');
    const text = injected(run) ?? '';
    expect(text).toContain(`you searched '${OPEN_MISS.question}' and got a MISS`);
    expect(text).toContain(`tenjin publish, searchId ${OPEN_MISS.searchId}`);
    expect(text).toContain(`tenjin candidate add <file> --search-id ${OPEN_MISS.searchId}`);
    expect(JSON.parse(run.stdout)).toHaveProperty('hookSpecificOutput.hookEventName', 'Stop');
  });

  it('nags exactly once: the second run is silent', async () => {
    await seedSearches([OPEN_MISS]);
    const first = await runScript(stopHookScript(dataDir), stopInput);
    expect(injected(first)).toContain('Open Tenjin loop');
    expect(await nagged()).toEqual([OPEN_MISS.searchId]);

    const second = await runScript(stopHookScript(dataDir), stopInput);
    expect(second.code).toBe(0);
    expect(second.stdout).toBe('');
    expect(await nagged()).toEqual([OPEN_MISS.searchId]);
  });

  it('says nothing about a MISS an outcome, publish, or candidate already closed', async () => {
    for (const by of ['outcome', 'publish', 'candidate']) {
      await seedSearches([{ ...OPEN_MISS, resolved: { by, at: new Date().toISOString() } }]);
      await rm(join(dataDir, 'hook-nags.json'), { force: true });
      const run = await runScript(stopHookScript(dataDir), stopInput);
      expect(run.stdout, by).toBe('');
    }
  });

  it('says nothing about a MISS older than the session window', async () => {
    await seedSearches([{ ...OPEN_MISS, minutesAgo: 9 * 60 }]);
    const run = await runScript(stopHookScript(dataDir), stopInput);
    expect(run.stdout).toBe('');
  });

  it('says nothing about a search that found candidates', async () => {
    await seedSearches([{ ...OPEN_MISS, decision: 'CANDIDATES' }]);
    const run = await runScript(stopHookScript(dataDir), stopInput);
    expect(run.stdout).toBe('');
  });

  it('says nothing at all when there is no local store', async () => {
    const run = await runScript(stopHookScript(dataDir), stopInput);
    expect(run.code).toBe(0);
    expect(run.stdout).toBe('');
    expect(run.stderr).toBe('');
  });

  it('survives a corrupt store without a word', async () => {
    await writeFile(join(dataDir, 'searches.json'), '{ not json');
    const run = await runScript(stopHookScript(dataDir), stopInput);
    expect(run.code).toBe(0);
    expect(run.stdout).toBe('');
  });

  it('caps a backlog at two open loops per turn', async () => {
    await seedSearches([
      OPEN_MISS,
      { ...OPEN_MISS, searchId: '44444444-4444-4444-8444-444444444444', minutesAgo: 25 },
      { ...OPEN_MISS, searchId: '55555555-5555-4555-8555-555555555555', minutesAgo: 30 },
    ]);
    const run = await runScript(stopHookScript(dataDir), stopInput);
    expect((injected(run) ?? '').split('\n')).toHaveLength(2);
    expect(await nagged()).toHaveLength(2);
  });

  // No network, no CLI boot: this one runs at the end of every turn.
  it('finishes in milliseconds', async () => {
    await seedSearches([OPEN_MISS]);
    const run = await runScript(stopHookScript(dataDir), stopInput);
    expect(run.ms).toBeLessThan(1500);
  });
});
