import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { spawn } from 'node:child_process';
import { createServer } from 'node:http';
import type { IncomingMessage, Server } from 'node:http';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  CAPTURE_REASON,
  PRIMER_TEXT,
  dispatchHookScript,
  sessionPrimerHookScript,
  stopHookScript,
  websearchHookScript,
} from './hook-scripts';
import {
  PUSH_LEDGER_FILE,
  pushContextHookScript,
  pushFailureHookScript,
  pushPromptHookScript,
  pushSubagentHookScript,
} from './push-scripts';

/**
 * The sidecar's arms, run as the REAL generated bytes against a real socket,
 * exactly as lib/hook-scripts.test.ts runs the two older hooks and for the same
 * reason: these files ship into a harness's settings.json, never go through the
 * bundler, and their whole contract is process behavior — what lands on stdout,
 * what reaches the wire, and what does not.
 *
 * The two facts every case here turns on: the team shelf is searched first and a
 * hit there makes NO request, and the research arm is the only arm that may deny
 * a tool call.
 */

let dataDir: string;
let scriptDir: string;
let server: Server | null = null;

beforeEach(async () => {
  dataDir = await mkdtemp(join(tmpdir(), 'tenjin-push-data-'));
  scriptDir = await mkdtemp(join(tmpdir(), 'tenjin-push-bin-'));
});

afterEach(async () => {
  if (server !== null) await new Promise<void>((res) => server!.close(() => res()));
  server = null;
  await rm(dataDir, { recursive: true, force: true });
  await rm(scriptDir, { recursive: true, force: true });
});

interface HookRun {
  code: number | null;
  stdout: string;
  stderr: string;
}

async function runScript(source: string, stdin: string): Promise<HookRun> {
  const path = join(scriptDir, `hook-${Math.random().toString(36).slice(2)}.mjs`);
  await writeFile(path, source, { mode: 0o755 });
  return await new Promise<HookRun>((resolve, reject) => {
    const child = spawn(process.execPath, [path], {
      stdio: ['pipe', 'pipe', 'pipe'],
      env: { PATH: process.env.PATH ?? '' },
    });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (c) => (stdout += String(c)));
    child.stderr.on('data', (c) => (stderr += String(c)));
    child.on('error', reject);
    child.on('close', (code) => resolve({ code, stdout, stderr }));
    child.stdin.end(stdin);
  });
}

interface StubRequest {
  url: string;
  body: string;
  base: string;
}

/** The marketplace, and the free-body endpoint a candidate url points at. */
async function serve(
  handler: (req: StubRequest) => { status: number; json: unknown } | 'hang',
): Promise<{
  baseUrl: string;
  hits: () => number;
  /** The `query` field of every search request that reached the wire. */
  queries: () => string[];
}> {
  let hits = 0;
  let base = '';
  const queries: string[] = [];
  const s = createServer((req: IncomingMessage, res) => {
    hits += 1;
    let body = '';
    req.on('data', (c) => (body += String(c)));
    req.on('end', () => {
      const url = req.url ?? '';
      if (url.startsWith('/api/search')) {
        try {
          queries.push(String((JSON.parse(body) as { query?: unknown }).query));
        } catch {
          queries.push('');
        }
      }
      const out = handler({ url, body, base });
      if (out === 'hang') return;
      res.writeHead(out.status, { 'content-type': 'application/json' });
      res.end(JSON.stringify(out.json));
    });
  });
  server = s;
  await new Promise<void>((res) => s.listen(0, '127.0.0.1', () => res()));
  const addr = s.address();
  const port = typeof addr === 'object' && addr !== null ? addr.port : 0;
  base = `http://127.0.0.1:${port}`;
  return { baseUrl: base, hits: () => hits, queries: () => queries };
}

const SEARCH_ID = '22222222-2222-4222-8222-222222222222';
const RESOURCE_ID = '11111111-1111-4111-8111-111111111111';
const BODY_MD = 'Pin the resolver to 4.1 and the parse stops throwing. Verified 2026-08-20.';
const SESSION = 'sess-1';

/**
 * A marketplace that answers with ONE candidate whose title is the query it was
 * asked. That makes the overlap score 1.0, which is what puts every case that
 * wants a strong hit on the strong path without hand-tuning words; a case that
 * wants a weak one passes its own title.
 */
const echo =
  (over: Record<string, unknown> = {}) =>
  (req: StubRequest): { status: number; json: unknown } => {
    if (req.url.startsWith('/api/search')) {
      let query: string;
      try {
        query = String((JSON.parse(req.body) as { query?: unknown }).query);
      } catch {
        query = '';
      }
      return {
        status: 200,
        json: {
          schemaVersion: 3,
          searchId: SEARCH_ID,
          items: [
            {
              resourceId: RESOURCE_ID,
              url: `${req.base}/@a/p`,
              title: query.slice(0, 190),
              price: '0',
              excerpt: 'the excerpt',
              creator: { handle: 'vraspar' },
              ...over,
            },
          ],
        },
      };
    }
    return { status: 200, json: { bodyMd: BODY_MD } };
  };

const miss = (req: StubRequest): { status: number; json: unknown } =>
  req.url.startsWith('/api/search')
    ? { status: 200, json: { schemaVersion: 3, searchId: SEARCH_ID, items: [] } }
    : { status: 404, json: {} };

async function writeConfig(config: Record<string, unknown>): Promise<void> {
  await writeFile(join(dataDir, 'config.json'), JSON.stringify(config, null, 2));
}

/** Push on, pointed at the stub. */
async function pushOn(baseUrl: string, hooks: Record<string, unknown> = {}): Promise<void> {
  await writeConfig({ baseUrl, hooks: { push: 'on', ...hooks } });
}

/** A note on the team shelf, in the format lib/notes.ts writes. */
async function writeNote(id: string, question: string, body: string): Promise<void> {
  const dir = join(dataDir, 'notes', 'notes');
  await mkdir(dir, { recursive: true });
  await writeFile(
    join(dir, `${id}.md`),
    [
      '---',
      `question: "${question}"`,
      'applies_to: [tenjin, drizzle]',
      'scope: "local dev"',
      'as_of: 2026-08-22',
      'author: vraspar',
      'source: ""',
      'visibility: team',
      '---',
      body,
      '',
    ].join('\n'),
  );
}

interface LedgerRow {
  [key: string]: unknown;
  trigger?: string;
  shelf?: string;
  action?: string;
  form?: string;
  deny?: boolean;
  reason?: string;
  candidate?: { id?: string; resourceId?: string; title?: string } | null;
}

async function ledger(): Promise<LedgerRow[]> {
  const path = join(dataDir, PUSH_LEDGER_FILE);
  if (!existsSync(path)) return [];
  const text = await readFile(path, 'utf8');
  return text
    .split('\n')
    .filter((line) => line.length > 0)
    .map((line) => JSON.parse(line) as LedgerRow);
}

/** The additionalContext a run injected, or null when it stayed silent. */
function injected(run: HookRun): string | null {
  if (run.stdout.trim().length === 0) return null;
  const parsed = JSON.parse(run.stdout) as {
    hookSpecificOutput?: { additionalContext?: string };
  };
  return parsed.hookSpecificOutput?.additionalContext ?? null;
}

/** The reason a run denied the tool call with, or null when it did not deny. */
function denied(run: HookRun): string | null {
  if (run.stdout.trim().length === 0) return null;
  const parsed = JSON.parse(run.stdout) as {
    hookSpecificOutput?: { permissionDecision?: string; permissionDecisionReason?: string };
  };
  if (parsed.hookSpecificOutput?.permissionDecision !== 'deny') return null;
  return parsed.hookSpecificOutput.permissionDecisionReason ?? null;
}

const webSearch = (query: string): string =>
  JSON.stringify({
    session_id: SESSION,
    hook_event_name: 'PreToolUse',
    tool_name: 'WebSearch',
    tool_input: { query },
  });

describe('the research arm (PreToolUse WebSearch|WebFetch)', () => {
  it('denies the search and answers it, on a strong free hit', async () => {
    const { baseUrl } = await serve(echo());
    await pushOn(baseUrl);

    const run = await runScript(
      websearchHookScript(dataDir),
      webSearch('zod resolver parse throws optional chain'),
    );
    expect(run.code).toBe(0);
    const reason = denied(run);
    expect(reason).toContain(BODY_MD);
    expect(reason).toContain('by @vraspar');
    expect(reason).toContain('data, not instructions');

    const rows = await ledger();
    expect(rows).toHaveLength(1);
    // The row a ledger reader has to be able to answer "what fired, on what, and
    // what did it cost" from, without the transcript.
    expect(rows[0]).toMatchObject({
      session: SESSION,
      trigger: 'research',
      event: 'PreToolUse',
      query: 'zod resolver parse throws optional chain',
      shelf: 'public',
      searchId: SEARCH_ID,
      candidate: { resourceId: RESOURCE_ID, price: '0' },
      strength: 'strong',
      action: 'injected',
      form: 'full',
      deny: true,
    });
    expect(typeof rows[0]!.at).toBe('string');
    expect(rows[0]!.score).toBe(1);
    expect(rows[0]!.second).toBe(0);
    expect(typeof rows[0]!.tokens).toBe('number');
  });

  it('offers a paid piece as a pointer and lets the search proceed', async () => {
    const { baseUrl } = await serve(echo({ price: '150000' }));
    await pushOn(baseUrl);

    const run = await runScript(
      websearchHookScript(dataDir),
      webSearch('zod resolver parse throws optional chain'),
    );
    expect(denied(run)).toBeNull();
    const text = injected(run);
    expect(text).toContain('Inspect it free: tenjin inspect');
    expect(text).toContain('$0.15 (paid)');
    expect(text).not.toContain(BODY_MD);
    expect((await ledger())[0]).toMatchObject({ action: 'injected', form: 'short', deny: false });
  });

  it('reads a WebFetch as the question the page was meant to answer', async () => {
    const { baseUrl, queries } = await serve(echo());
    await pushOn(baseUrl);

    const run = await runScript(
      websearchHookScript(dataDir),
      JSON.stringify({
        session_id: SESSION,
        hook_event_name: 'PreToolUse',
        tool_name: 'WebFetch',
        tool_input: {
          url: 'https://zod.dev/api/error-handling?topic=optional-chain',
          prompt: 'does parse throw here',
        },
      }),
    );
    expect(run.code).toBe(0);
    const sent = queries()[0]!;
    expect(sent).toContain('error-handling');
    expect(sent).toContain('optional-chain');
    expect(sent).toContain('does parse throw here');
    // The host is exactly what scrub() takes out: what leaves is the shape of the
    // question, never the address it was going to.
    expect(sent).not.toContain('zod.dev');
    expect(denied(run)).toContain(BODY_MD);
  });

  it('leaves WebSearch alone and WebFetch untouched when push is off', async () => {
    const { baseUrl, hits } = await serve(echo());
    await writeConfig({ baseUrl });

    const search = await runScript(websearchHookScript(dataDir), webSearch('zod parse throws'));
    expect(denied(search)).toBeNull();
    expect(injected(search)).toContain('Tenjin lists a free answer');

    const fetched = await runScript(
      websearchHookScript(dataDir),
      JSON.stringify({
        hook_event_name: 'PreToolUse',
        tool_name: 'WebFetch',
        tool_input: { url: 'https://zod.dev/api', prompt: 'summarize' },
      }),
    );
    expect(fetched.stdout).toBe('');
    // One request, from the WebSearch: the fetch never reached the wire.
    expect(hits()).toBe(1);
    expect(await ledger()).toEqual([]);
  });

  it('says nothing on a miss, and records why', async () => {
    const { baseUrl } = await serve(miss);
    await pushOn(baseUrl);
    const run = await runScript(websearchHookScript(dataDir), webSearch('zod parse throws here'));
    expect(run.stdout).toBe('');
    expect((await ledger())[0]).toMatchObject({ action: 'skipped', reason: 'miss' });
  });
});

describe('the team shelf', () => {
  it('answers from a note without touching the network', async () => {
    const { baseUrl, hits } = await serve(echo());
    await pushOn(baseUrl);
    await writeNote(
      '20260822-k3x9q2',
      'Does the read beacon fire for hand-seeded posts?',
      'It does not. The beacon needs a real session row, so hand-seeded posts read as zero.',
    );

    const run = await runScript(
      websearchHookScript(dataDir),
      webSearch('read beacon hand-seeded posts tenjin'),
    );
    expect(run.code).toBe(0);
    const text = injected(run);
    expect(text).toContain('team note · by vraspar');
    expect(text).toContain('applies to tenjin, drizzle');
    expect(text).toContain('The beacon needs a real session row');
    // A note is ours: it is never worth denying a tool call over, and it never
    // costs a request.
    expect(denied(run)).toBeNull();
    expect(hits()).toBe(0);

    const rows = await ledger();
    expect(rows).toHaveLength(1);
    expect(rows[0]).toMatchObject({
      trigger: 'research',
      shelf: 'team',
      candidate: {
        id: '20260822-k3x9q2',
        title: 'Does the read beacon fire for hand-seeded posts?',
      },
      strength: 'strong',
      action: 'injected',
      form: 'full',
      deny: false,
    });
    expect(rows[0]!.searchId).toBeUndefined();
  });

  it('falls through to the marketplace when no note is close enough', async () => {
    const { baseUrl, hits } = await serve(echo());
    await pushOn(baseUrl);
    await writeNote(
      '20260822-k3x9q2',
      'Does the read beacon fire for hand-seeded posts?',
      'It does not.',
    );

    const run = await runScript(
      websearchHookScript(dataDir),
      webSearch('stripe webhook signature clock skew'),
    );
    expect(hits()).toBeGreaterThan(0);
    expect((await ledger())[0]).toMatchObject({ shelf: 'public' });
    expect(denied(run)).toContain(BODY_MD);
  });
});

describe('the prompt arm (UserPromptSubmit)', () => {
  const prompt = (text: string): string =>
    JSON.stringify({ session_id: SESSION, hook_event_name: 'UserPromptSubmit', prompt: text });

  const QUESTION =
    'The zod resolver throws on an optional chain during parse and I need to know whether pinning helps';

  it('injects on the same turn, and scrubs the paths out of what it sends', async () => {
    const { baseUrl, queries } = await serve(echo());
    await pushOn(baseUrl);

    const run = await runScript(
      pushPromptHookScript(dataDir),
      prompt(`${QUESTION} in /Users/vraspar/work/app/src/thing.ts`),
    );
    expect(run.code).toBe(0);
    expect(injected(run)).toContain(BODY_MD);
    expect(queries()[0]).not.toContain('/Users/vraspar');
    expect((await ledger())[0]).toMatchObject({
      trigger: 'prompt',
      event: 'UserPromptSubmit',
      action: 'injected',
      // The prompt arm cannot deny: there is no tool call to deny.
      deny: false,
    });
  });

  it('skips a short prompt and a slash command without asking anything', async () => {
    const { baseUrl, hits } = await serve(echo());
    await pushOn(baseUrl);

    const short = await runScript(pushPromptHookScript(dataDir), prompt('yes, do that'));
    expect(short.stdout).toBe('');
    const slash = await runScript(pushPromptHookScript(dataDir), prompt(`/review ${QUESTION}`));
    expect(slash.stdout).toBe('');
    expect(hits()).toBe(0);
    expect(await ledger()).toEqual([]);
  });

  it('reads the older user_input spelling too', async () => {
    const { baseUrl } = await serve(echo());
    await pushOn(baseUrl);
    const run = await runScript(
      pushPromptHookScript(dataDir),
      JSON.stringify({
        session_id: SESSION,
        hook_event_name: 'UserPromptSubmit',
        user_input: QUESTION,
      }),
    );
    expect(injected(run)).toContain(BODY_MD);
  });

  it('stays silent when the marketplace never answers', async () => {
    const { baseUrl } = await serve(() => 'hang');
    await pushOn(baseUrl);
    const run = await runScript(pushPromptHookScript(dataDir), prompt(QUESTION));
    expect(run.code).toBe(0);
    expect(run.stdout).toBe('');
    expect(run.stderr).toBe('');
    expect((await ledger())[0]).toMatchObject({ action: 'skipped', reason: 'no-answer' });
  });

  it('does nothing at all with push off', async () => {
    const { baseUrl, hits } = await serve(echo());
    await writeConfig({ baseUrl });
    const run = await runScript(pushPromptHookScript(dataDir), prompt(QUESTION));
    expect(run.stdout).toBe('');
    expect(hits()).toBe(0);
  });
});

describe('the failure arm (PostToolUse Bash)', () => {
  const failure = (): string =>
    JSON.stringify({
      session_id: SESSION,
      hook_event_name: 'PostToolUse',
      tool_name: 'Bash',
      tool_input: { command: 'pnpm install left-pad' },
      tool_response: {
        stdout: '',
        stderr: "Error: Cannot find module 'left-pad' required by the vitest resolver",
        exit_code: 1,
        interrupted: false,
      },
    });

  it('names the package the failure was about, then never asks twice', async () => {
    const { baseUrl, hits, queries } = await serve(echo());
    await pushOn(baseUrl);

    const first = await runScript(pushFailureHookScript(dataDir), failure());
    expect(injected(first)).toContain(BODY_MD);
    expect(queries()[0]).toContain('left-pad');
    const askedOnce = hits();

    // The same command re-run is the same problem. Both PostToolUse and
    // PostToolUseFailure can fire for one failure, too.
    const second = await runScript(pushFailureHookScript(dataDir), failure());
    expect(second.stdout).toBe('');
    expect(hits()).toBe(askedOnce);
    expect(await ledger()).toHaveLength(1);
  });

  it('reads the top-level error string of a PostToolUseFailure', async () => {
    const { baseUrl, queries } = await serve(echo());
    await pushOn(baseUrl);
    const run = await runScript(
      pushFailureHookScript(dataDir),
      JSON.stringify({
        session_id: SESSION,
        hook_event_name: 'PostToolUseFailure',
        tool_name: 'Bash',
        tool_input: { command: 'pnpm test' },
        error: "Exit code 1\nTypeError: Cannot find module 'left-pad' from the vitest resolver",
      }),
    );
    expect(queries()[0]).toContain('left-pad');
    expect((await ledger())[0]).toMatchObject({
      trigger: 'failure',
      event: 'PostToolUseFailure',
      action: 'injected',
    });
    expect(injected(run)).toContain(BODY_MD);
  });

  /**
   * An auth failure is the failure this arm fires on most often, so the token in
   * it is the common case and not the edge. Nothing credential-shaped may reach
   * the wire, and nothing credential-shaped may reach the ledger either: the
   * ledger row carries the same string the request did.
   */
  it('strips the credential out of an auth failure before it leaves the machine', async () => {
    const { baseUrl, queries } = await serve(echo());
    await pushOn(baseUrl);
    const run = await runScript(
      pushFailureHookScript(dataDir),
      JSON.stringify({
        session_id: SESSION,
        hook_event_name: 'PostToolUseFailure',
        tool_name: 'Bash',
        tool_input: { command: 'git push origin main' },
        error:
          'fatal: Authentication failed for token ghp_16C7e42F292c6912E7710c838347Ae178B4a using account vraspar-ops',
      }),
    );
    expect(run.code).toBe(0);
    const sent = queries()[0] ?? '';
    expect(sent).toContain('Authentication');
    expect(sent).not.toContain('ghp_');
    expect(sent).not.toContain('16C7e42F292c6912E7710c838347Ae178B4a');
    const rows = await ledger();
    expect(String(rows[0]!.query)).not.toContain('ghp_');
  });
});

describe('the subagent arm (SubagentStart)', () => {
  it('hands the subagent what the dispatch found, once', async () => {
    const { baseUrl } = await serve(echo());
    await pushOn(baseUrl);

    const dispatched = await runScript(
      dispatchHookScript(dataDir),
      JSON.stringify({
        session_id: SESSION,
        hook_event_name: 'PreToolUse',
        tool_name: 'Task',
        tool_input: {
          prompt:
            'Find out whether the zod resolver throws on an optional chain during parse, and what pinning changes',
        },
      }),
    );
    // The lead still gets its pointer lines; the cache is the extra.
    expect(injected(dispatched)).toContain('Tenjin lists');

    const start = JSON.stringify({
      session_id: SESSION,
      hook_event_name: 'SubagentStart',
      agent_id: 'a1',
      agent_type: 'general-purpose',
    });
    const first = await runScript(pushSubagentHookScript(dataDir), start);
    expect(injected(first)).toContain(BODY_MD);
    expect((await ledger())[0]).toMatchObject({
      trigger: 'subagent',
      event: 'SubagentStart',
      agentType: 'general-purpose',
      action: 'injected',
      deny: false,
    });

    // Consumed: a second subagent from the same dispatch gets nothing.
    const second = await runScript(pushSubagentHookScript(dataDir), start);
    expect(second.stdout).toBe('');
  });
});

describe('the context arm (log-only)', () => {
  it('logs the packages a Read named and says nothing to the model', async () => {
    const { baseUrl } = await serve(echo());
    await pushOn(baseUrl);
    const file = join(scriptDir, 'thing.ts');
    await writeFile(file, "import { z } from 'zod';\nexport const s = z.string();\n");

    const run = await runScript(
      pushContextHookScript(dataDir),
      JSON.stringify({
        session_id: SESSION,
        hook_event_name: 'PostToolUse',
        tool_name: 'Read',
        tool_input: { file_path: file },
      }),
    );
    expect(run.stdout).toBe('');
    const rows = await ledger();
    expect(rows).toHaveLength(1);
    expect(rows[0]).toMatchObject({ trigger: 'read', action: 'logged', form: 'full' });
    expect(rows[0]!.query).toContain('zod');
  });
});

describe('the team shelf pull (SessionStart)', () => {
  it('spawns the pull without waiting for it, and prints the primer anyway', async () => {
    // A `.git` that is not a repo: the pull fails, detached, and the hook has
    // already moved on. The primer is what the harness is waiting for.
    await mkdir(join(dataDir, 'notes', '.git'), { recursive: true });
    await writeConfig({});
    const run = await runScript(
      sessionPrimerHookScript(dataDir),
      JSON.stringify({ session_id: SESSION, hook_event_name: 'SessionStart', source: 'startup' }),
    );
    expect(run.code).toBe(0);
    expect(run.stderr).toBe('');
    expect(injected(run)).toBe(PRIMER_TEXT);
  });
});

describe('the capture ask (Stop)', () => {
  const stopInput = JSON.stringify({ session_id: SESSION, hook_event_name: 'Stop', cwd: '/tmp' });

  /** A recorded search stamped with this session: the research signal. */
  async function writeSearchSignal(): Promise<void> {
    await writeFile(
      join(dataDir, 'searches.json'),
      JSON.stringify({
        schemaVersion: 1,
        searches: [
          {
            searchId: SEARCH_ID,
            at: new Date().toISOString(),
            question: 'zod parse',
            decision: 'CANDIDATES',
            candidates: [],
            source: 'cli',
            sessionId: SESSION,
          },
        ],
      }),
    );
  }

  it('blocks once, with nothing else on stdout, then lets the session end', async () => {
    await writeConfig({ hooks: { capture: 'block' } });
    await writeSearchSignal();

    const first = await runScript(stopHookScript(dataDir), stopInput);
    expect(first.code).toBe(0);
    expect(JSON.parse(first.stdout)).toEqual({ decision: 'block', reason: CAPTURE_REASON });
    // The marker `notes add` / `notes none` reads to learn which session to clear.
    expect(await readFile(join(dataDir, 'push', 'capture-pending'), 'utf8')).toBe(SESSION);

    const second = await runScript(stopHookScript(dataDir), stopInput);
    expect(second.stdout).toBe('');
  });

  it('takes a push-ledger row as the research signal too', async () => {
    await writeConfig({ hooks: { capture: 'block' } });
    await mkdir(dataDir, { recursive: true });
    await writeFile(
      join(dataDir, PUSH_LEDGER_FILE),
      `${JSON.stringify({ at: new Date().toISOString(), session: SESSION, trigger: 'prompt', action: 'skipped' })}\n`,
    );
    const run = await runScript(stopHookScript(dataDir), stopInput);
    expect(JSON.parse(run.stdout)).toEqual({ decision: 'block', reason: CAPTURE_REASON });
  });

  it('says the same thing as context under nudge, and blocks nothing', async () => {
    await writeConfig({ hooks: { capture: 'nudge' } });
    await writeSearchSignal();
    const run = await runScript(stopHookScript(dataDir), stopInput);
    expect(run.stdout).not.toContain('"decision"');
    expect(injected(run)).toBe(CAPTURE_REASON);
  });

  it('asks nothing of a session that did no research, or with capture off', async () => {
    await writeConfig({ hooks: { capture: 'block' } });
    const quiet = await runScript(stopHookScript(dataDir), stopInput);
    expect(quiet.stdout).toBe('');

    await writeConfig({});
    await writeSearchSignal();
    const off = await runScript(stopHookScript(dataDir), stopInput);
    expect(off.stdout).toBe('');
  });
});
