// Vendors the zero-install skill: fetch the canonical skills.md and write it to
// skills/tenjin/SKILL.md verbatim, with a "do not hand-edit" banner spliced in.
// Dependency-free (Node >=22 global fetch) so drift CI needs no install. The
// transform is a pure string splice: same fetched bytes -> byte-identical output,
// which is what lets `git diff --exit-code` be a meaningful drift signal.
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SOURCE_URL = 'https://tenjin.blog/skills.md';

// Resolved from the script's own location, not process.cwd(), so the output lands
// in the repo regardless of where `node scripts/sync-skill.mjs` is invoked from.
const OUTPUT_PATH = resolve(
  fileURLToPath(import.meta.url),
  '..',
  '..',
  'skills',
  'tenjin',
  'SKILL.md',
);

// Spliced immediately AFTER the frontmatter's closing `---`. The exact wording is
// load-bearing: an agent that hits a stale vendored copy is told where the truth
// lives.
const BANNER = `<!--
  Synced from https://tenjin.blog/skills.md; that URL is canonical and always current.
  Do not edit this file by hand; run \`pnpm sync:skill\` to refresh it.
  If anything here fails, fetch the live version and follow that instead.
-->
`;

// Opening `---`, the YAML body (non-greedy), then the closing `---` line — captured
// whole (including its trailing newline) so the banner slots in right after it.
const FRONTMATTER_RE = /^(---\n[\s\S]*?\n---\n)/;

function fail(message) {
  console.error(`sync-skill: ${message}`);
  process.exit(1);
}

// Bounded so a hung connection fails a local run instead of hanging it; CI has its
// own 5-minute job timeout on top.
const res = await fetch(SOURCE_URL, { signal: AbortSignal.timeout(30_000) }).catch((err) =>
  fail(`could not fetch ${SOURCE_URL}: ${err.message}`),
);
if (!res.ok) fail(`fetching ${SOURCE_URL} returned HTTP ${res.status} ${res.statusText}`);

const source = await res.text();
const match = FRONTMATTER_RE.exec(source);
if (match === null)
  fail(`no YAML frontmatter found in ${SOURCE_URL}; refusing to write a malformed skill`);

const output = match[1] + BANNER + source.slice(match[1].length);

await mkdir(dirname(OUTPUT_PATH), { recursive: true });
await writeFile(OUTPUT_PATH, output, 'utf8');
